### ISSUE TITLE
Get artist data from the iframe in the user's playlist

### ISSUE THREAD

**Issue by erikbenedict** [erikbenedict/fruit-preserves#29]
## TODO:

- [x] figure out how to grab the artist name from the iframe in the users playlist
- [x] create event listener for addArtistBtn
- [x] add artist name data to event listener to be used in the future for Ticketmaster API
